### ISSUE TITLE
Worlds should create an array of entities

### ISSUE THREAD

**Issue by RustyBamboo** [dim35/CEN3031-Project#14]
- Add player to be in the list of entities
- Each entity comes from it's own class with the same functions
For example:
## Monster Class
- `move()` <-- Some sort of path planning every tick
- `update()` <-- Actually do the move and redraw
## Player Class
- `move()` <-- Take in inputs
- `update()` <-- Actually do the move and redraw

Then inside the world we will have:
```
var allEntites = []
for e in allEntities:
    e.move()
    e.update()
```

**Comment by RustyBamboo** [comment]
This will allow for a more stable integration for networking

**Comment by AleksandrHovhannisyan** [comment]
Makes sense. I'll explore Godot's polymorphism stuff a bit more to see if it's possible to create an "entity" scene and then make extension scenes for players and mobs.
